# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Realsense&TMzuTXji.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(796, 637)
        MainWindow.setStyleSheet(u"background-color: rgb(244, 244, 244);")
        self.ipaddress = QAction(MainWindow)
        self.ipaddress.setObjectName(u"ipaddress")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 751, 41))
        font = QFont()
        font.setFamily(u"\ub9d1\uc740 \uace0\ub515")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color: rgb(29, 98, 182)")
        self.openGLWidget = QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setObjectName(u"openGLWidget")
        self.openGLWidget.setGeometry(QRect(20, 90, 501, 321))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(560, 60, 201, 351))
        font1 = QFont()
        font1.setFamily(u"\ub9d1\uc740 \uace0\ub515")
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setWeight(75)
        self.groupBox.setFont(font1)
        self.groupBox.setStyleSheet(u"\n"
"background-color: rgb(244, 244, 244);")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 40, 61, 16))
        font2 = QFont()
        font2.setFamily(u"\ub9d1\uc740 \uace0\ub515")
        font2.setPointSize(10)
        font2.setBold(False)
        font2.setWeight(50)
        self.label_3.setFont(font2)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 70, 61, 16))
        self.label_4.setFont(font2)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 100, 61, 16))
        self.label_5.setFont(font2)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 130, 61, 16))
        self.label_6.setFont(font2)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 160, 61, 16))
        self.label_7.setFont(font2)
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 190, 61, 16))
        self.label_8.setFont(font2)
        self.x_off = QLineEdit(self.groupBox)
        self.x_off.setObjectName(u"x_off")
        self.x_off.setGeometry(QRect(100, 40, 71, 21))
        self.x_off.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.y_off = QLineEdit(self.groupBox)
        self.y_off.setObjectName(u"y_off")
        self.y_off.setGeometry(QRect(100, 70, 71, 21))
        self.y_off.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.place_on = QPushButton(self.groupBox)
        self.place_on.setObjectName(u"place_on")
        self.place_on.setGeometry(QRect(10, 220, 181, 28))
        font3 = QFont()
        font3.setFamily(u"\ub9d1\uc740 \uace0\ub515")
        font3.setBold(True)
        font3.setWeight(75)
        self.place_on.setFont(font3)
        self.pick_on = QPushButton(self.groupBox)
        self.pick_on.setObjectName(u"pick_on")
        self.pick_on.setGeometry(QRect(10, 250, 181, 28))
        self.pick_on.setFont(font3)
        self.reset = QPushButton(self.groupBox)
        self.reset.setObjectName(u"reset")
        self.reset.setGeometry(QRect(140, 320, 51, 28))
        self.auto_on = QPushButton(self.groupBox)
        self.auto_on.setObjectName(u"auto_on")
        self.auto_on.setGeometry(QRect(10, 280, 181, 28))
        self.auto_on.setFont(font3)
        self.z_off = QLineEdit(self.groupBox)
        self.z_off.setObjectName(u"z_off")
        self.z_off.setGeometry(QRect(100, 100, 71, 21))
        self.z_off.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.yaw_off = QLineEdit(self.groupBox)
        self.yaw_off.setObjectName(u"yaw_off")
        self.yaw_off.setGeometry(QRect(100, 130, 71, 21))
        self.yaw_off.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pitch_off = QLineEdit(self.groupBox)
        self.pitch_off.setObjectName(u"pitch_off")
        self.pitch_off.setGeometry(QRect(100, 160, 71, 21))
        self.pitch_off.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.roll_off = QLineEdit(self.groupBox)
        self.roll_off.setObjectName(u"roll_off")
        self.roll_off.setGeometry(QRect(100, 190, 71, 21))
        self.roll_off.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(30, 450, 571, 121))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 569, 119))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 60, 211, 21))
        self.label_2.setFont(font1)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 420, 741, 161))
        self.groupBox_2.setFont(font1)
        self.get_depth = QPushButton(self.groupBox_2)
        self.get_depth.setObjectName(u"get_depth")
        self.get_depth.setGeometry(QRect(590, 20, 141, 131))
        font4 = QFont()
        font4.setFamily(u"\ub9d1\uc740 \uace0\ub515")
        font4.setPointSize(15)
        font4.setBold(True)
        font4.setWeight(75)
        self.get_depth.setFont(font4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.groupBox_2.raise_()
        self.label.raise_()
        self.openGLWidget.raise_()
        self.groupBox.raise_()
        self.scrollArea.raise_()
        self.label_2.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 796, 26))
        self.menu = QMenu(self.menuBar)
        self.menu.setObjectName(u"menu")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menu.menuAction())
        self.menu.addAction(self.ipaddress)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.ipaddress.setText(QCoreApplication.translate("MainWindow", u"IP Address", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"REALSENSE & TM ROBOT  PICK & PLACE", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\ub85c\ubd07 \uc88c\ud45c", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"X_off", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Y_off", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Z_off", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Yaw_off", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Pitch_off", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Roll_off", None))
        self.place_on.setText(QCoreApplication.translate("MainWindow", u"Place ON", None))
        self.pick_on.setText(QCoreApplication.translate("MainWindow", u"Pick ON", None))
        self.reset.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.auto_on.setText(QCoreApplication.translate("MainWindow", u"Auto ON", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"REALSENSE CAMERA", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\uc6cc\ud06c \uc88c\ud45c", None))
        self.get_depth.setText(QCoreApplication.translate("MainWindow", u"Get Depth", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\uc124\uc815", None))
    # retranslateUi

